# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: git clone https://github.com/galloj/IFJ22_Tester.git testsJirka

      - name: Install dependencies
        run: sudo apt-get -y install valgrind

      - name: make
        run: |
         make
         cd testsJirka
         sudo ./test.py ../ifj_comp ../ic22int

      - name: valgrind
        run: |
          valgrind --leak-check=yes ./ifj_comp < tests/faktorial_rek.php